/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.records;


import edu.java.domain.jooq.tables.GithubLink;

import java.beans.ConstructorProperties;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GithubLinkRecord extends UpdatableRecordImpl<GithubLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>GITHUB_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>GITHUB_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>GITHUB_LINK.LAST_PULL_REQUEST_DATE</code>.
     */
    public void setLastPullRequestDate(@Nullable OffsetDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>GITHUB_LINK.LAST_PULL_REQUEST_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastPullRequestDate() {
        return (OffsetDateTime) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    @NotNull
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GithubLinkRecord
     */
    public GithubLinkRecord() {
        super(GithubLink.GITHUB_LINK);
    }

    /**
     * Create a detached, initialised GithubLinkRecord
     */
    @ConstructorProperties({ "linkId", "lastPullRequestDate" })
    public GithubLinkRecord(@NotNull Long linkId, @Nullable OffsetDateTime lastPullRequestDate) {
        super(GithubLink.GITHUB_LINK);

        setLinkId(linkId);
        setLastPullRequestDate(lastPullRequestDate);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised GithubLinkRecord
     */
    public GithubLinkRecord(edu.java.domain.jooq.tables.pojos.GithubLink value) {
        super(GithubLink.GITHUB_LINK);

        if (value != null) {
            setLinkId(value.getLinkId());
            setLastPullRequestDate(value.getLastPullRequestDate());
            resetChangedOnNotNull();
        }
    }
}
