app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 10s

  database-access-type: jdbc

  github_base_url: ${GITHUB_BASE_URL:https://api.github.com/}
  stackoverflow_base_url: ${STACK_OVERFLOW_BASE_URL:https://api.stackexchange.com/2.3/}
  bot_api_url: ${BOT_API_URL:http://localhost:8090}

  link-updates-topic-name: link-updates
  use-queue: true
spring:
  application:
    name: scrapper
  config:
    import: optional:file:.env[.properties]

  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

kafka:
  bootstrapServers: localhost:29092
  clientId: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
