app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 10s

  database-access-type: jpa

  github_base_url: ${GITHUB_BASE_URL:https://api.github.com/}
  stackoverflow_base_url: ${STACK_OVERFLOW_BASE_URL:https://api.stackexchange.com/2.3/}
  bot_api_url: ${BOT_API_URL:http://localhost:8090}

  retry:
    retryItems:
      - client-name: bot
        type: linear
        max-attempts: 5
        min-backoff: 1s
        max-backoff: 15s
        increment: 3s
        error-codes: 500

spring:
  application:
    name: scrapper
  config:
    import: optional:file:.env[.properties]

  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  codec:
    max-in-memory-size: 20MB

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
