app:
  scheduler:
    enable: true
    interval: 60s
    force-check-delay: 10s

  database-access-type: jdbc

  github_base_url: ${GITHUB_BASE_URL:https://api.github.com/}
  stackoverflow_base_url: ${STACK_OVERFLOW_BASE_URL:https://api.stackexchange.com/2.3/}
  bot_api_url: ${BOT_API_URL:http://localhost:8090}

  link-updates-topic-name: link-updates
  use-queue: false

  retry:
    retryItems:
      - client-name: bot
        type: linear
        max-attempts: 5
        min-backoff: 1s
        max-backoff: 15s
        increment: 3s
        error-codes: 500

      - client-name: github
        type: exponential
        max-attempts: 2
        min-backoff: 1s
        max-backoff: 15s
        jitter: 0.75
        error-codes: 404

      - client-name: stackoverflow
        type: constant
        max-attempts: 5
        min-backoff: 1s
        max-backoff: 15s
        error-codes:
          - 404
          - 500

spring:
  application:
    name: scrapper
  config:
    import: optional:file:.env[.properties]

  liquibase:
    enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s

kafka:
  bootstrapServers: localhost:29092
  clientId: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui


bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      http-status-code: TOO_MANY_REQUESTS
      http-response-body: "Too much requests! Try again later."
      url: /api/.*
      rate-limits:
        - bandwidths:
            - capacity: 60
              time: 1
              unit: minutes
          cache-key: getRemoteAddr()
