app:
  telegram-token: ${TELEGRAM_BOT_TOKEN}
  scrapper_api_url: ${SCRAPPER_API_URL:http://localhost:8080}\

  retry:
    retryItems:
      - client-name: scrapper
        type: linear
        max-attempts: 5
        min-backoff: 1s
        max-backoff: 15s
        increment: 3s
        error-codes: 500

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
