app:
  telegram-token: ${TELEGRAM_BOT_TOKEN}
  scrapper_api_url: ${SCRAPPER_API_URL:http://localhost:8080}

  scrapper-topic-name: link-updates

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
  config:
    import: optional:file:.env[.properties]
  liquibase:
    enabled: false

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui


kafka:
  bootstrapServers: localhost:29092
  groupId: bot
  autoOffsetReset: latest
  maxPollIntervalMs: 300_000
  enableAutoCommit: false
  concurrency: 1
