/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables;

import edu.java.domain.jooq.DefaultSchema;
import edu.java.domain.jooq.Keys;
import edu.java.domain.jooq.tables.Link.LinkPath;
import edu.java.domain.jooq.tables.records.GithubLinkRecord;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GithubLink extends TableImpl<GithubLinkRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>GITHUB_LINK</code>
     */
    public static final GithubLink GITHUB_LINK = new GithubLink();

    /**
     * The class holding records for this type
     */
    @Override
    @NotNull
    public Class<GithubLinkRecord> getRecordType() {
        return GithubLinkRecord.class;
    }

    /**
     * The column <code>GITHUB_LINK.LINK_ID</code>.
     */
    public final TableField<GithubLinkRecord, Long> LINK_ID =
        createField(DSL.name("LINK_ID"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>GITHUB_LINK.LAST_PULL_REQUEST_DATE</code>.
     */
    public final TableField<GithubLinkRecord, OffsetDateTime> LAST_PULL_REQUEST_DATE =
        createField(DSL.name("LAST_PULL_REQUEST_DATE"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private GithubLink(Name alias, Table<GithubLinkRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private GithubLink(Name alias, Table<GithubLinkRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>GITHUB_LINK</code> table reference
     */
    public GithubLink(String alias) {
        this(DSL.name(alias), GITHUB_LINK);
    }

    /**
     * Create an aliased <code>GITHUB_LINK</code> table reference
     */
    public GithubLink(Name alias) {
        this(alias, GITHUB_LINK);
    }

    /**
     * Create a <code>GITHUB_LINK</code> table reference
     */
    public GithubLink() {
        this(DSL.name("GITHUB_LINK"), null);
    }

    public <O extends Record> GithubLink(
        Table<O> path,
        ForeignKey<O, GithubLinkRecord> childPath,
        InverseForeignKey<O, GithubLinkRecord> parentPath
    ) {
        super(path, childPath, parentPath, GITHUB_LINK);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class GithubLinkPath extends GithubLink implements Path<GithubLinkRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> GithubLinkPath(
            Table<O> path,
            ForeignKey<O, GithubLinkRecord> childPath,
            InverseForeignKey<O, GithubLinkRecord> parentPath
        ) {
            super(path, childPath, parentPath);
        }

        private GithubLinkPath(Name alias, Table<GithubLinkRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public GithubLinkPath as(String alias) {
            return new GithubLinkPath(DSL.name(alias), this);
        }

        @Override
        public GithubLinkPath as(Name alias) {
            return new GithubLinkPath(alias, this);
        }

        @Override
        public GithubLinkPath as(Table<?> alias) {
            return new GithubLinkPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    @Nullable
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    @NotNull
    public UniqueKey<GithubLinkRecord> getPrimaryKey() {
        return Keys.CONSTRAINT_D8;
    }

    @Override
    @NotNull
    public List<ForeignKey<GithubLinkRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CONSTRAINT_D);
    }

    private transient LinkPath _link;

    /**
     * Get the implicit join path to the <code>PUBLIC.LINK</code> table.
     */
    public LinkPath link() {
        if (_link == null) {
            _link = new LinkPath(this, Keys.CONSTRAINT_D, null);
        }

        return _link;
    }

    @Override
    @NotNull
    public GithubLink as(String alias) {
        return new GithubLink(DSL.name(alias), this);
    }

    @Override
    @NotNull
    public GithubLink as(Name alias) {
        return new GithubLink(alias, this);
    }

    @Override
    @NotNull
    public GithubLink as(Table<?> alias) {
        return new GithubLink(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLink rename(String name) {
        return new GithubLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLink rename(Name name) {
        return new GithubLink(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    @NotNull
    public GithubLink rename(Table<?> name) {
        return new GithubLink(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public GithubLink where(Condition condition) {
        return new GithubLink(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public GithubLink where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public GithubLink where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public GithubLink where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public GithubLink where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public GithubLink where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public GithubLink where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    @PlainSQL
    public GithubLink where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public GithubLink whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @NotNull
    public GithubLink whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
