/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq.tables.pojos;

import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;
import javax.annotation.processing.Generated;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class GithubLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private OffsetDateTime lastPullRequestDate;

    public GithubLink() {
    }

    public GithubLink(GithubLink value) {
        this.linkId = value.linkId;
        this.lastPullRequestDate = value.lastPullRequestDate;
    }

    @ConstructorProperties({"linkId", "lastPullRequestDate"})
    public GithubLink(
        @NotNull Long linkId,
        @Nullable OffsetDateTime lastPullRequestDate
    ) {
        this.linkId = linkId;
        this.lastPullRequestDate = lastPullRequestDate;
    }

    /**
     * Getter for <code>GITHUB_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>GITHUB_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>GITHUB_LINK.LAST_PULL_REQUEST_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastPullRequestDate() {
        return this.lastPullRequestDate;
    }

    /**
     * Setter for <code>GITHUB_LINK.LAST_PULL_REQUEST_DATE</code>.
     */
    public void setLastPullRequestDate(@Nullable OffsetDateTime lastPullRequestDate) {
        this.lastPullRequestDate = lastPullRequestDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final GithubLink other = (GithubLink) obj;
        if (this.linkId == null) {
            if (other.linkId != null) {
                return false;
            }
        } else if (!this.linkId.equals(other.linkId)) {
            return false;
        }
        if (this.lastPullRequestDate == null) {
            if (other.lastPullRequestDate != null) {
                return false;
            }
        } else if (!this.lastPullRequestDate.equals(other.lastPullRequestDate)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.lastPullRequestDate == null) ? 0 : this.lastPullRequestDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("GithubLink (");

        sb.append(linkId);
        sb.append(", ").append(lastPullRequestDate);

        sb.append(")");
        return sb.toString();
    }
}
