/*
 * This file is generated by jOOQ.
 */
package edu.java.domain.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.19.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StackoverflowLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long linkId;
    private OffsetDateTime lastAnswerDate;

    public StackoverflowLink() {}

    public StackoverflowLink(StackoverflowLink value) {
        this.linkId = value.linkId;
        this.lastAnswerDate = value.lastAnswerDate;
    }

    @ConstructorProperties({ "linkId", "lastAnswerDate" })
    public StackoverflowLink(
        @NotNull Long linkId,
        @Nullable OffsetDateTime lastAnswerDate
    ) {
        this.linkId = linkId;
        this.lastAnswerDate = lastAnswerDate;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>STACKOVERFLOW_LINK.LAST_ANSWER_DATE</code>.
     */
    @Nullable
    public OffsetDateTime getLastAnswerDate() {
        return this.lastAnswerDate;
    }

    /**
     * Setter for <code>STACKOVERFLOW_LINK.LAST_ANSWER_DATE</code>.
     */
    public void setLastAnswerDate(@Nullable OffsetDateTime lastAnswerDate) {
        this.lastAnswerDate = lastAnswerDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final StackoverflowLink other = (StackoverflowLink) obj;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.lastAnswerDate == null) {
            if (other.lastAnswerDate != null)
                return false;
        }
        else if (!this.lastAnswerDate.equals(other.lastAnswerDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.lastAnswerDate == null) ? 0 : this.lastAnswerDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("StackoverflowLink (");

        sb.append(linkId);
        sb.append(", ").append(lastAnswerDate);

        sb.append(")");
        return sb.toString();
    }
}
